/* Generated by the photo pipeline — do not hand-edit.
   Every photograph here is the author's own, taken on site.
   PHOTOS[<intervention id>] = {src, place, caption, w, h}      */
const PHOTOS = {
  "open-hours": {
    "src": "images/interventions/open-hours.jpg",
    "place": "Margravine Cemetery",
    "caption": "Opening hours posted on the gate, month by month",
    "w": 1000,
    "h": 1333
  },
  "threshold-edge": {
    "src": "images/interventions/threshold-edge.jpg",
    "place": "The Sherriff Centre",
    "caption": "The doors propped open onto the street",
    "w": 1000,
    "h": 667
  },
  "signage": {
    "src": "images/interventions/signage.jpg",
    "place": "The Sherriff Centre",
    "caption": "'In a church? Yes! Plus much more.'",
    "w": 1000,
    "h": 1500
  },
  "seating-outside": {
    "src": "images/interventions/seating-outside.jpg",
    "place": "St Stephen Walbrook",
    "caption": "Benches and shade in the churchyard garden",
    "w": 1000,
    "h": 750
  },
  "lighting": {
    "src": "images/interventions/lighting.jpg",
    "place": "Garden Museum",
    "caption": "The nave relit for a gallery, warm and layered",
    "w": 1000,
    "h": 1333
  },
  "acoustics": {
    "src": "images/interventions/acoustics.jpg",
    "place": "Garden Museum",
    "caption": "Rugs, upholstered chairs and a soft wall in a stone corridor",
    "w": 1000,
    "h": 750
  },
  "domestic-comfort": {
    "src": "images/interventions/domestic-comfort.jpg",
    "place": "The Sherriff Centre",
    "caption": "An armchair and a fireplace inside the church",
    "w": 1000,
    "h": 667
  },
  "paths": {
    "src": "images/interventions/paths.jpg",
    "place": "Margravine Cemetery",
    "caption": "One clear surfaced route, cut through the planting",
    "w": 1000,
    "h": 750
  },
  "context-fit": {
    "src": "images/interventions/context-fit.jpg",
    "place": "Garden Museum",
    "caption": "The new extension answering the churchyard it sits in",
    "w": 1000,
    "h": 750
  },
  "sensory": {
    "src": "images/interventions/sensory.jpg",
    "place": "Garden Museum",
    "caption": "A quiet corner kept low-stimulus, off the main route",
    "w": 1000,
    "h": 750
  },
  "transparency": {
    "src": "images/interventions/transparency.jpg",
    "place": "Bow",
    "caption": "A glazed frontage that shows the activity inside",
    "w": 1000,
    "h": 667
  },
  "local-noticeboard": {
    "src": "images/interventions/local-noticeboard.jpg",
    "place": "Grand Junction",
    "caption": "A board that carries the neighbourhood, not only the institution",
    "w": 1000,
    "h": 667
  },
  "small-welcome": {
    "src": "images/interventions/small-welcome.jpg",
    "place": "Garden Museum",
    "caption": "Bike stands inside the churchyard",
    "w": 1000,
    "h": 750
  },
  "community-art": {
    "src": "images/interventions/community-art.jpg",
    "place": "Canary Wharf",
    "caption": "A tree of visitors' written notes in a public concourse",
    "w": 1000,
    "h": 750
  },
  "indoor-green": {
    "src": "images/interventions/indoor-green.jpg",
    "place": "Garden Museum",
    "caption": "Planting brought inside the church",
    "w": 1000,
    "h": 750
  },
  "post-office": {
    "src": "images/interventions/post-office.jpg",
    "place": "The Sherriff Centre",
    "caption": "Post office, caf\u00e9 and debt advice, on one wall",
    "w": 1000,
    "h": 667
  },
  "advice-clinic": {
    "src": "images/interventions/advice-clinic.jpg",
    "place": "St Patrick's Wapping",
    "caption": "Advice and support leaflets by the door",
    "w": 1000,
    "h": 1500
  },
  "food-project": {
    "src": "images/interventions/food-project.jpg",
    "place": "The Sherriff Centre",
    "caption": "The community fridge and donation shelves",
    "w": 1000,
    "h": 667
  },
  "warm-space": {
    "src": "images/interventions/warm-space.jpg",
    "place": "Garden Museum",
    "caption": "Free seating in the corridor \u2014 no ticket needed",
    "w": 1000,
    "h": 750
  },
  "servery": {
    "src": "images/interventions/servery.jpg",
    "place": "The Sherriff Centre",
    "caption": "The servery counter in the aisle",
    "w": 1000,
    "h": 667
  },
  "cafe": {
    "src": "images/interventions/cafe.jpg",
    "place": "Grand Junction",
    "caption": "The canal-side caf\u00e9 in the new wing",
    "w": 1000,
    "h": 667
  },
  "community-meal": {
    "src": "images/interventions/community-meal.jpg",
    "place": "The Sherriff Centre",
    "caption": "Tables laid in the nave",
    "w": 1000,
    "h": 667
  },
  "concerts": {
    "src": "images/interventions/concerts.jpg",
    "place": "St Stephen Walbrook",
    "caption": "Lunchtime jazz, advertised on the pavement",
    "w": 1000,
    "h": 750
  },
  "exhibition": {
    "src": "images/interventions/exhibition.jpg",
    "place": "St Patrick's Wapping",
    "caption": "A local history banner standing in the aisle",
    "w": 1000,
    "h": 667
  },
  "hire": {
    "src": "images/interventions/hire.jpg",
    "place": "Garden Museum",
    "caption": "The nave laid out with tables for an event",
    "w": 1000,
    "h": 750
  },
  "library-culture": {
    "src": "images/interventions/library-culture.jpg",
    "place": "Bow",
    "caption": "Library shelves, visible from the street",
    "w": 1000,
    "h": 667
  },
  "esol": {
    "src": "images/interventions/esol.jpg",
    "place": "Garden Museum",
    "caption": "A learning table set up in the nave",
    "w": 1000,
    "h": 750
  },
  "wellbeing": {
    "src": "images/interventions/wellbeing.jpg",
    "place": "The Sherriff Centre",
    "caption": "A class set up in the chapel",
    "w": 1000,
    "h": 667
  },
  "creative-workshop": {
    "src": "images/interventions/creative-workshop.jpg",
    "place": "Garden Museum",
    "caption": "A making station in the middle of the atrium",
    "w": 1000,
    "h": 750
  },
  "health-outreach": {
    "src": "images/interventions/health-outreach.jpg",
    "place": "St Patrick's Wapping",
    "caption": "Health and support notices inside the door",
    "w": 1000,
    "h": 667
  },
  "toddler": {
    "src": "images/interventions/toddler.jpg",
    "place": "St Patrick's Wapping",
    "caption": "A children's corner in the aisle",
    "w": 1000,
    "h": 667
  },
  "soft-play": {
    "src": "images/interventions/soft-play.jpg",
    "place": "The Sherriff Centre",
    "caption": "Two-storey soft play in the north aisle",
    "w": 1000,
    "h": 1500
  },
  "youth-club": {
    "src": "images/interventions/youth-club.jpg",
    "place": "Grand Junction",
    "caption": "The youth club advertised on the railings",
    "w": 1000,
    "h": 667
  },
  "playground": {
    "src": "images/interventions/playground.jpg",
    "place": "Paddington",
    "caption": "The playground on the green beside the church",
    "w": 1000,
    "h": 667
  },
  "workspace": {
    "src": "images/interventions/workspace.jpg",
    "place": "Bow",
    "caption": "A community centre letting rooms and workspace",
    "w": 1000,
    "h": 667
  },
  "meeting-rooms": {
    "src": "images/interventions/meeting-rooms.jpg",
    "place": "Garden Museum",
    "caption": "A small room that can be let by the hour",
    "w": 1000,
    "h": 1333
  },
  "market": {
    "src": "images/interventions/market.jpg",
    "place": "Canary Wharf",
    "caption": "A programmed stall set down in a public concourse",
    "w": 1000,
    "h": 750
  },
  "quiet-room": {
    "src": "images/interventions/quiet-room.jpg",
    "place": "St Patrick's Wapping",
    "caption": "A side chapel kept quiet and available",
    "w": 1000,
    "h": 750
  },
  "memorial": {
    "src": "images/interventions/memorial.jpg",
    "place": "Tower Hamlets Cemetery Park",
    "caption": "A tended grave inside a public park",
    "w": 1000,
    "h": 667
  },
  "multifaith": {
    "src": "images/interventions/multifaith.jpg",
    "place": "Canary Wharf",
    "caption": "An annual faith events programme in a shared building",
    "w": 1000,
    "h": 1333
  },
  "churchyard-open": {
    "src": "images/interventions/churchyard-open.jpg",
    "place": "St John's Wapping",
    "caption": "The churchyard used as a route between streets",
    "w": 1000,
    "h": 750
  },
  "community-garden": {
    "src": "images/interventions/community-garden.jpg",
    "place": "St Patrick's Wapping",
    "caption": "The community garden announced at the gate",
    "w": 1000,
    "h": 667
  },
  "nature-reserve": {
    "src": "images/interventions/nature-reserve.jpg",
    "place": "Tower Hamlets Cemetery Park",
    "caption": "Interpretation for an urban nature reserve",
    "w": 1000,
    "h": 667
  },
  "greening": {
    "src": "images/interventions/greening.jpg",
    "place": "Garden Museum",
    "caption": "A planted courtyard on what was hard standing",
    "w": 1000,
    "h": 750
  },
  "accessible-wc": {
    "src": "images/interventions/accessible-wc.jpg",
    "place": "Garden Museum",
    "caption": "The new-build wing \u2014 where the WCs, kitchen and lift went, because the church could not take them",
    "w": 1000,
    "h": 1333
  },
  "step-free": {
    "src": "images/interventions/step-free.jpg",
    "place": "St George's Bloomsbury",
    "caption": "The steps that decide who can get in",
    "w": 1000,
    "h": 1333
  },
  "movable-seating": {
    "src": "images/interventions/movable-seating.jpg",
    "place": "St Patrick's Wapping",
    "caption": "Fixed pews \u2014 the starting condition",
    "w": 1000,
    "h": 667
  },
  "heating": {
    "src": "images/interventions/heating.jpg",
    "place": "Garden Museum",
    "caption": "One small, well-lined room \u2014 heat this rather than the whole volume",
    "w": 1000,
    "h": 1333
  },
  "storage": {
    "src": "images/interventions/storage.jpg",
    "place": "St Patrick's Wapping",
    "caption": "Chairs and tables stacked in the aisle, with nowhere to go",
    "w": 1000,
    "h": 1500
  },
  "extension": {
    "src": "images/interventions/extension.jpg",
    "place": "Garden Museum",
    "caption": "The new wing wrapped around the churchyard",
    "w": 1000,
    "h": 750
  },
  "insertion": {
    "src": "images/interventions/insertion.jpg",
    "place": "Garden Museum",
    "caption": "A new timber structure standing free inside the church",
    "w": 1000,
    "h": 750
  },
  "timetable": {
    "src": "images/interventions/timetable.jpg",
    "place": "Grand Junction",
    "caption": "The week, posted where people pass",
    "w": 1000,
    "h": 667
  },
  "meanwhile": {
    "src": "images/interventions/meanwhile.jpg",
    "place": "Chelsea Old Church",
    "caption": "A churchyard shut behind railings, waiting for a decision",
    "w": 1000,
    "h": 1333
  },
  "late-opening": {
    "src": "images/interventions/late-opening.jpg",
    "place": "Paddington Old Cemetery",
    "caption": "Closing time chalked up fresh each day",
    "w": 1000,
    "h": 667
  },
  "trail": {
    "src": "images/interventions/trail.jpg",
    "place": "Bow",
    "caption": "A local wayfinding map linking sites together",
    "w": 1000,
    "h": 667
  },
  "friends-group": {
    "src": "images/interventions/friends-group.jpg",
    "place": "Tower Hamlets Cemetery Park",
    "caption": "Held by a charity and its volunteers",
    "w": 1000,
    "h": 667
  },
  "partnership": {
    "src": "images/interventions/partnership.jpg",
    "place": "Grand Junction",
    "caption": "Parish, diocese and a development trust in one building",
    "w": 1000,
    "h": 667
  },
  "trading-sub": {
    "src": "images/interventions/trading-sub.jpg",
    "place": "Grand Junction",
    "caption": "The caf\u00e9 bar \u2014 trading income that pays for the free programme",
    "w": 1000,
    "h": 667
  },
  "digital": {
    "src": "images/interventions/digital.jpg",
    "place": "St Patrick's Wapping",
    "caption": "A contactless donation point by the door",
    "w": 1000,
    "h": 667
  },
  "coproduce": {
    "src": "images/interventions/coproduce.jpg",
    "place": "Garden Museum",
    "caption": "Draft boards for a community exhibition, still being made",
    "w": 1000,
    "h": 1333
  }
};

const CASE_CAPTIONS = {
  "garden-museum": [
    "The west door \u2014 the medieval arch fitted with automatic glass doors",
    "The courtyard garden, looked in on from the caf\u00e9 and galleries",
    "The shop, on the way from the galleries to the garden",
    "Permanent history integrated into the space, at the altar"
  ],
  "sheriff-centre": [
    "St James' from the street \u2014 a working parish church",
    "'In a church? Yes! Plus much more.' \u2014 the post office sign",
    "The Sanctuary Caf\u00e9 in the south aisle",
    "Hullabaloo soft play, two storeys in the north aisle"
  ],
  "grand-junction": [
    "St Mary Magdalene's from the green, with benches along the path",
    "The caf\u00e9 in the new wing",
    "The programme noticeboard on the green",
    "Inside the caf\u00e9 \u2014 the building's everyday way in"
  ],
  "paddington-old-cemetery": [
    "The main avenue \u2014 the site's clearest public route",
    "The entrance gates, with opening times",
    "The twin chapels, closed and under repair",
    "Interpretation at the entrance"
  ],
  "tower-hamlets-cemetery-park": [
    "A path through the burial landscape, with a bench off it",
    "A Friends sign at an entrance, with opening times",
    "Graves held in ivy \u2014 remembrance and nature together",
    "'Plants & People' \u2014 interpretation for an urban nature reserve"
  ],
  "st-patricks-wapping": [
    "St Patrick's from Green Bank",
    "St Patrick's Kitchen Garden, announced beside the gate",
    "The nave, in fixed pews",
    "Children's books on the aisle wall \u2014 no seating, no signage"
  ],
  "st-johns-churchyard-wapping": [
    "The path through the churchyard \u2014 a shortcut",
    "Gravestones set against the wall \u2014 an evolution of sacred space",
    "The Thomas Rainsborough plaque, set high on the wall",
    "Open grass, unprogrammed"
  ],
  "st-stephen-walbrook": [
    "St Stephen Walbrook in the City, beside a coffee chain",
    "The noticeboard: a warm welcome to all, to visit, to reflect, to pray",
    "Rush Hour Jazz, advertised on the pavement",
    "The churchyard garden \u2014 benches, shade and a fountain"
  ],
  "lambeth-palace-library": [
    "The library's street edge on Lambeth Palace Road",
    "Metal fins and the library's name above the entrance",
    "The approach along the main road",
    "The boundary wall, holding the street"
  ]
};
